### ISSUE TITLE
不能用了吗？

### ISSUE THREAD

**Issue by daxian2022** [Potato-py/ipInfoSearch#1]

**Comment by Wh7t3zZ** [comment]
查到一个就结束了

**Comment by potato-security** [comment]
很抱歉您遇到的问题，请先参考一下解决办法：

1、确保您的网络通信不存在问题，可以在module文件夹中各个py文件查看api，确定是否都可以访问（部分国外ip不能访问api，被运营商拉黑了）
2、因为多线程原因，对于性能低的电脑可能会存在递归溢出问题（本人开发时是在mac上进行的，这个问题只能有空再解决了），临时解决方案 请在ipInfoSearch.py头部添加
```
import sys
sys.setrecursionlimit(10000)
```

若还存在问题，请提供运行环境及报错代码。我将及时更新代码解决您的问题。

**Comment by yinjuzhishi** [comment]
跑单个ip也跑不出来

**Comment by potato-security** [comment]
部分国外ip不能访问api，被运营商拉黑了,请更换网络
